version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "standard"
  dialect = "typescript"

[[transformers]]
name = "standardjs"
enabled = true